spring.application.name=backend

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/solifund
spring.datasource.username=solifund
spring.datasource.password=solifund
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
# JWT
jwt.secret=v2wTb6BkHGKE1DDV+x9Di22q1WT6SC6oLwAIYMZ7Hgk=
jwt.expiration=86400000

# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
